export const products = [
    { name: "Bluetooth Speaker", price: 2500, category: "electronics", rating: 4.2 },
    { name: "T-Shirt", price: 800, category: "fashion", rating: 4.0 },
    { name: "Smartphone", price: 15000, category: "electronics", rating: 4.3 },
    { name: "Jeans", price: 2200, category: "fashion", rating: 4.4 },
    { name: "Sneakers", price: 2500, category: "fashion", rating: 4.5 },
    { name: "Charging Adapter", price: 800, category: "electronics", rating: 4.0 },
    { name: "Bracelet", price: 5500, category: "fashion", rating: 4.2 },
    { name: "Laptop", price: 55000, category: "electronics", rating: 4.6 },
    { name: "Python", price: 799, category: "books", rating: 4.5 },
    { name: "Notebook", price: 120, category: "books", rating: 4.0 },
    { name: "USB Cable", price: 99, category: "electronics", rating: 3.8 },
    { name: "Football", price: 1200, category: "sports", rating: 4.4 },
    { name: "Novel", price: 450, category: "books", rating: 4.3 },
    { name: "Table Lamp", price: 1800, category: "home", rating: 4.2 },
    { name: "Extension Board", price: 400, category: "electronics", rating: 4.1 },
    { name: "Data Structures Book", price: 600, category: "books", rating: 4.7 },
    { name: "Web Development", price: 999, category: "books", rating: 4.6 },
    { name: "Ring", price: 400, category: "fashion", rating: 3.9 },
    { name: "Wall Clock", price: 900, category: "home", rating: 4.1 },
    { name: "Resistance Band", price: 200, category: "sports", rating: 3.9 },
    { name: "Skipping Rope", price: 300, category: "sports", rating: 4.1 },
    { name: "Cow Statue", price: 900, category: "home", rating: 3.8 },
    { name: "Ram Pratima", price: 100000, category: "home", rating: 4.9 },
    { name: "Water Bottle", price: 500, category: "home", rating: 4.0 },
    { name: "Cricket Bat", price: 3200, category: "sports", rating: 4.6 },
    { name: "Gripper", price: 600, category: "sports", rating: 4.0 },
];
